### ISSUE TITLE
javascrpt build is failing

### ISSUE THREAD

**Issue by d2-d2** [LINKIWI/modern-paste#13]
This one is failing too

```
Javascript build started.
Compiling app/static/js/misc/APIDocumentationController.js --> app/static/build/js/misc/APIDocumentationController.js
Traceback (most recent call last):
  File "build/build_js.py", line 107, in <module>
    '--js_output_file', js_output_file,
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by LINKIWI** [comment]
On some systems, the build process doesn't automatically generate the directories for the compiled JS and CSS files. You can work around this temporarily by making these directories yourself before compiling:

```bash
mkdir -p app/static/build/css
mkdir -p app/static/build/js
```

**Comment by d2-d2** [comment]
Hmm, I investigated this a bit and it turns out that 'java' was the 'problem'. Actually, it was not installed on my system and due to this message is misleading it wasn't clear what's going on during this process. First, I thought the same, that directories are missing and installer assuming their existence without checking/creating them. But it wasn't it. After installing openjdk, everything was OK.

Occasionally, during 'test' phase, tests are failing with 'deadlock' message. I can easily reproduce it and show you, but this is subject for another 'Issue' report.

**Comment by LINKIWI** [comment]
Java is indeed a necessary prerequisite for building the application and it is currently in the installation guide. However, I will reformat the README to make this more clear. Thanks for pointing that out.

I haven't seen test failures as a result of a deadlock before, and that seems very strange. Could you pleaes open up another issue and post a stacktrace of the test failures?

**Comment by LINKIWI** [comment]
I've updated the README with more concise prerequisite requirements.

Additionally, the `make` procedure is now designed to fail if you don't have `java` installed so that the error is more apparent. I'm considering this fixed.
