### ISSUE TITLE
[Improvement] File/Image uploader

### ISSUE THREAD

**Issue by barbour-em** [LINKIWI/modern-paste#17]
Would you consider adding the functionality to create a file or image paste similar to that of [susepaste](http://paste.opensuse.org/)  or imgur? I think this would be a great addition.

If you are unavailable to work on this, with a few pointers I might be able to contribute.

**Comment by relrod** [comment]
:+1: for this!

**Comment by LINKIWI** [comment]
Thanks for the feedback. This is something I'd be happy to work on implementing.

This will probably be implemented as allowing the user to attach files to a regular paste. In the paste view interface, the client might be able to detect the content type of the attachments, and display a preview if it's an image.

Feel free to comment with more suggestions about this functionality. I'll update this thread with progress as I develop.

**Comment by LINKIWI** [comment]
This feature is being developed in the `paste-attachments` branch. Feel free to checkout the branch and look around.

A deployment of `paste-attachments` is currently live on [dev.modernpaste.com](https://dev.modernpaste.com) if you want to see what it looks like so far. You can check the Git SHA of the deployed commit at https://dev.modernpaste.com/version.

**Comment by LINKIWI** [comment]
Closing as this is now implemented and available in the `dev` branch.

**Comment by barbour-em** [comment]
Thanks for implementing this. It works great for me. :+1:
