### ISSUE TITLE
LDAP Support

### ISSUE THREAD

**Issue by unixtime** [LINKIWI/modern-paste#18]
Thank you for creating this awesome Package!! 
Is there LDAP/AD integration on the road-map?

Thanks in advance.

**Comment by LINKIWI** [comment]
At this time, there are no plans for LDAP/AD integration. However, there exist many Flask libraries for this purpose like [Flask-LDAP](http://flask-ldap.readthedocs.io/en/latest/) that would make it easy to add an additional authentication layer to the existing user account system.
