### ISSUE TITLE
uni-sans seems to be non-FOSS

### ISSUE THREAD

**Issue by relrod** [LINKIWI/modern-paste#19]
I can't seem to find the source for the `uni-sans` font included with modern-paste. As part of getting modern-paste deployed in Fedora Infrastructure, we'd have to replace this (we have a policy of only running FOSS software in the infrastructure).

Would you be willing to accept a patch that replaces this font out with a visually-similar FOSS alternative? We could have the Fedora Design team make some recommendations if necessary.

Thoughts on this?

**Comment by mairin** [comment]
Here are some recommends:

- Open Sans Light (http://www.opensans.com/)
- Overpass Light (http://overpassfont.org/)
- Junction (https://www.theleagueofmoveabletype.com/junction - it has a light version too, I did screenshot below with Regular) 
- Advent Pro (https://www.google.com/fonts/specimen/Advent+Pro)

![fonts-modernpaste svg](https://cloud.githubusercontent.com/assets/799683/16047106/c167e8ee-321c-11e6-9dd4-8864744161ac.png)

**Comment by LINKIWI** [comment]
The font that ships with the master branch is a core component of Modern Paste's design language, so as that stands, I'm not going to change the included font. However, MP is open source: you're always free to swap out the included font for another one in your own deployment. MP was architected to be modular enough that you can swap and replace most components without much incident.

I'd be willing to change the same of the CSS class "uni-sans" to a more generic name, but it will still pull the font files from the same location (with a more generic file name). The only action required on your end is to swap out those .ttfs for different ones.

**Comment by Freso** [comment]
If you end up going with this and fork it, please let me/us know here. I'd much prefer to use a fully-FOSS version of this for personal use as well.

**Comment by LINKIWI** [comment]
Commit f5afb58ec7a83e271a009e99927d8bd5378ac7bc (currently in the `dev` branch) genericizes the font names. Feel free to swap out the included `sans-serif*.ttf` files for whichever font(s) you like.
