### ISSUE TITLE
Size limit for attachments not working as intended

### ISSUE THREAD

**Issue by xstnc** [LINKIWI/modern-paste#23]
When setting the 

```
# Allow only paste attachments below a certain size threshold, in MB
# Set this to 0 for an unlimited file size.
MAX_ATTACHMENT_SIZE = 0
```
and

```
# Choose to allow paste attachments
# This will allow for users to attach files and images to pastes. If disabled, the MAX_ATTACHMENT_SIZE and
# ATTACHMENTS_DIR configuration constants will be ignored.
ENABLE_PASTE_ATTACHMENTS = True
```
The uploads are still disabled, and the error message prompts the following message: 

> There was an error processing your request. This file's size exceeds the limit of 0 MB imposed by the server administrator.

When setting `MAX_ATTACHMENT_SIZE` larger than `0`, the uploads works.

**Comment by LINKIWI** [comment]
Thanks for the report. Sorry that it took so long to get around to this. I can reproduce, and it seems like there was just a little bit of missing logic in the client-side validation routine. This should be fixed by 5d3d7a405ada323618e957fdd01e93683c6226de.
