### ISSUE TITLE
Remote MySQL Server

### ISSUE THREAD

**Issue by vectr0n** [LINKIWI/modern-paste#25]
Is it possible to use a remote mysql server, all tests fail as it's looking for the socket and not reading the correct info from /etc/mysql/my.cnf and see no option to set a mysql db host in the config.

Keep getting error `OperationalError: (_mysql_exceptions.OperationalError) (2002, 'Can\'t connect to local MySQL server through socket \'/var/run/mysqld/mysqld.sock\' (2 "No such file or directory")')` when running `make`

**Comment by vectr0n** [comment]
Figured it out with editing the myqsl host in file `app/flask_config.py`.

**Comment by LINKIWI** [comment]
Glad to hear you worked around it. I've added `DATABASE_HOST` to config.py to make this easier: f081a181cae5449ad9fc42378aa5de9cf5db3424
