### ISSUE TITLE
URL is forced to be root of example.com?

### ISSUE THREAD

**Issue by DMinsky** [LINKIWI/modern-paste#29]
Is is possible to run modern-paste at for example **example.com/modernpaste** not at **modernpaste.example.com**? I spend some time playing with apache and uri/*.py files without any success.

Currently, I have "regular" php in my /var/www/html/ directory configured to be shown at **example.com**. And modern-paste in /var/www/wsgi/ directory with following config.

`WSGIScriptAlias /modernpaste /var/www/wsgi/mp/modern_paste.wsgi
<Directory /var/www/wsgi/modernpaste/>
    Order deny,allow
    Allow from all
</Directory>`

Which I want to be shown on **example.com/modernpaste**. But, because of all internal code rely on absolute urls all I see is 404 with missing css and js files.

**Comment by LINKIWI** [comment]
I don't believe this is possible, as the application's URI and routing infrastructure assumes paths relative to `/` (as you have pointed out).

You could run the service on a local port and ask Apache to reverse proxy the location `/modernpaste` to that port. This should work.

However, supporting this functionality at the application level is not currently a priority.
