### ISSUE TITLE
Wrong expiration date

### ISSUE THREAD

**Issue by isnog00d** [LINKIWI/modern-paste#32]
[EXPIRES JANUARY 19, 2038](https://demo.modernpaste.com/paste/LNGlQ2g7UNmt86lYwlGXkRQDRB9BZ42MRHb4Tt8RGHY=). 
But setted date is much closer.

Repro:
1. >new paste
2. Set tommorow as exp. date

Reproducible on public demo

**Comment by LINKIWI** [comment]
Confirmed reproducible, looking into this now.

**Comment by LINKIWI** [comment]
Looks like this is caused client-side by https://github.com/LINKIWI/modern-paste/blob/dev/app/static/js/paste/PostController.js#L147. The client is supplying an expiry time in milliseconds (standard for JS) while the server expects all timestamps to be in seconds (standard for Python). Can't believe I never caught this bug.

**Comment by LINKIWI** [comment]
699b6b42c96243387225e80f809c1619ed6da986 fixes this issue and is now deployed on dev.modernpaste.com and demo.modernpaste.com.
