### ISSUE TITLE
errors while compiling

### ISSUE THREAD

**Issue by andrewm659** [LINKIWI/modern-paste#45]
Is this looking for a local mysql server? Can this not be a remote?

Also I'm running this on CentOS 7.3 with all latest packages.

pip install -r requirements.txt
Collecting coverage (from -r requirements.txt (line 1))
  Downloading coverage-4.4.1-cp27-cp27mu-manylinux1_x86_64.whl (193kB)
    100% |████████████████████████████████| 194kB 2.2MB/s
Collecting coveralls (from -r requirements.txt (line 2))
  Downloading coveralls-1.1-py2.py3-none-any.whl
Collecting flask (from -r requirements.txt (line 3))
  Downloading Flask-0.12.2-py2.py3-none-any.whl (83kB)
    100% |████████████████████████████████| 92kB 3.6MB/s
Collecting flask-login (from -r requirements.txt (line 4))
  Downloading Flask_Login-0.4.0-py2.py3-none-any.whl
Collecting flask-sqlalchemy (from -r requirements.txt (line 5))
  Downloading Flask_SQLAlchemy-2.2-py2.py3-none-any.whl
Collecting flask-testing (from -r requirements.txt (line 6))
  Downloading Flask-Testing-0.6.2.tar.gz (129kB)
    100% |████████████████████████████████| 133kB 2.6MB/s
Collecting mock (from -r requirements.txt (line 7))
  Downloading mock-2.0.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 3.8MB/s
Collecting mysql-python (from -r requirements.txt (line 8))
  Downloading MySQL-python-1.2.5.zip (108kB)
    100% |████████████████████████████████| 112kB 2.9MB/s
    Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-q_PWOr/mysql-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-q_PWOr/mysql-python/
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
make[1]: *** [dependencies] Error 1
make[1]: Leaving directory `/var/www/html/modern-paste'
make: *** [all] Error 2

**Comment by fazlerabbi37** [comment]
`sudo pip install pystan` solved it for me.
