### ISSUE TITLE
not compiling on centos 7

### ISSUE THREAD

**Issue by andrewm659** [LINKIWI/modern-paste#46]
Requirement already satisfied (use --upgrade to upgrade): urllib3<1.22,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests->-r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe>=0.23 in /usr/lib64/python2.7/site-packages (from Jinja2>=2.4->flask->-r requirements.txt (line 3))
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
pre-commit install
pre-commit installed at /var/www/html/modern-paste/.git/hooks/pre-commit
git submodule init
git submodule update
make[1]: Leaving directory `/var/www/html/modern-paste'
make check-style
make[1]: Entering directory `/var/www/html/modern-paste'
pre-commit run --all-files
[WARNING] git://github.com/pre-commit/pre-commit-hooks uses legacy hooks.yaml to provide hooks.
In newer versions, this file is called .pre-commit-hooks.yaml
This will work in this version of pre-commit but will be removed at a later time.
If `pre-commit autoupdate` does not silence this warning consider making an issue / pull request.
[WARNING] git://github.com/pre-commit/mirrors-scss-lint uses legacy hooks.yaml to provide hooks.
In newer versions, this file is called .pre-commit-hooks.yaml
This will work in this version of pre-commit but will be removed at a later time.
If `pre-commit autoupdate` does not silence this warning consider making an issue / pull request.
Trim Trailing Whitespace.................................................Passed
Check JSON...............................................................Passed
Check Yaml...............................................................Passed
Check for merge conflicts................................................Passed
Check python ast.........................................................Passed
Debug Statements (Python)................................................Passed
Fix End of Files.........................................................Passed
Flake8...................................................................Failed
hookid: flake8

app/config.py:1:1: F401 'constants' imported but unused
app/config.py:16:1: E265 block comment should start with '# '
app/config.py:17:21: F821 undefined name 'modern_paste'

Fix requirements.txt.....................................................Passed
scss_lint................................................................Passed
make[1]: *** [check-style] Error 1
make[1]: Leaving directory `/var/www/html/modern-paste'
make: *** [all] Error 2

**Comment by LINKIWI** [comment]
For anyone else stumbling across this issue: `make` will be default run all code checks and unit tests. You're free to skip all of this if you're interested only in installing.
