### ISSUE TITLE
Password hashing for reset?

### ISSUE THREAD

**Issue by hexmonkey** [LINKIWI/modern-paste#66]
Is there any way to reset a user's forgotten password? 
If not, is there a way I can generate a hash and insert it manually into the database?

**Comment by LINKIWI** [comment]
> Is there any way to reset a user's forgotten password?

No.

> If not, is there a way I can generate a hash and insert it manually into the database?

Yes, you can replace the password hash with `util.cryptography.secure_hash(password)` (run this from a Python shell). Then you should be able to login with that passsord.
